defmodule HousingApp.Repo.TenantMigrations.AddTenantToTimePeriods do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:time_periods, prefix: prefix()) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "time_periods_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:time_periods, "time_periods_tenant_id_fkey")

    alter table(:time_periods, prefix: prefix()) do
      remove :tenant_id
    end
  end
end