defmodule HousingApp.Repo.TenantMigrations.AddFormToApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applications, prefix: prefix()) do
      remove :version
      remove :json_schema

      add :form_id,
          references(:forms,
            column: :id,
            name: "applications_form_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:applications, "applications_form_id_fkey")

    alter table(:applications, prefix: prefix()) do
      remove :form_id
      add :json_schema, :text, null: false
      add :version, :bigint, null: false, default: 1
    end
  end
end
