defmodule HousingApp.Repo.TenantMigrations.CreateApplicationSubmissionsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:form_submissions, ["data"], using: "GIN")

    create index(:form_submissions, ["form_id"])

    create index(:form_submissions, ["user_tenant_id"])

    create table(:application_submissions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "application_submissions_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_tenant_id,
          references(:user_tenants,
            column: :id,
            name: "application_submissions_user_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :application_id,
          references(:applications,
            column: :id,
            name: "application_submissions_application_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :data, :map, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :archived_at, :utc_datetime_usec
    end

    create index(:application_submissions, ["data"], using: "GIN")

    create index(:application_submissions, ["application_id"])

    create index(:application_submissions, ["user_tenant_id"])
  end

  def down do
    drop constraint(:application_submissions, "application_submissions_tenant_id_fkey")

    drop constraint(:application_submissions, "application_submissions_user_tenant_id_fkey")

    drop constraint(:application_submissions, "application_submissions_application_id_fkey")

    drop_if_exists index(:application_submissions, ["user_tenant_id"],
                     name: "application_submissions_user_tenant_id_index"
                   )

    drop_if_exists index(:application_submissions, ["application_id"],
                     name: "application_submissions_application_id_index"
                   )

    drop_if_exists index(:application_submissions, ["data"],
                     name: "application_submissions_data_index"
                   )

    drop table(:application_submissions, prefix: prefix())

    drop_if_exists index(:form_submissions, ["user_tenant_id"],
                     name: "form_submissions_user_tenant_id_index"
                   )

    drop_if_exists index(:form_submissions, ["form_id"], name: "form_submissions_form_id_index")

    drop_if_exists index(:form_submissions, ["data"], name: "form_submissions_data_index")
  end
end
