defmodule HousingApp.Repo.TenantMigrations.AddApplicationSubmissionToBookings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bookings, prefix: prefix()) do
      add :application_submission_id,
          references(:application_submissions,
            column: :id,
            name: "bookings_application_submission_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:bookings, "bookings_application_submission_id_fkey")

    alter table(:bookings, prefix: prefix()) do
      remove :application_submission_id
    end
  end
end