defmodule HousingApp.Repo.TenantMigrations.AddSubmissionTypeToApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applications, prefix: prefix()) do
      add :submission_type, :text, null: false, default: "once"
    end
  end

  def down do
    alter table(:applications, prefix: prefix()) do
      remove :submission_type
    end
  end
end