defmodule HousingApp.Repo.TenantMigrations.ChangeBookingsFieldsToDate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bookings, prefix: prefix()) do
      modify :end_at, :date
      modify :start_at, :date
    end
  end

  def down do
    alter table(:bookings, prefix: prefix()) do
      modify :start_at, :utc_datetime_usec
      modify :end_at, :utc_datetime_usec
    end
  end
end