defmodule HousingApp.Repo.TenantMigrations.RenameBuildingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:buildings), :floors, to: :floor_count

    rename table(:buildings), :rooms, to: :room_count
  end

  def down do
    rename table(:buildings), :room_count, to: :rooms

    rename table(:buildings), :floor_count, to: :floors
  end
end
