defmodule HousingApp.Repo.TenantMigrations.AddFormSubmissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:form_submissions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "form_submissions_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_tenant_id,
          references(:user_tenants,
            column: :id,
            name: "form_submissions_user_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :form_id,
          references(:forms,
            column: :id,
            name: "form_submissions_form_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :data, :map, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:form_submissions, "form_submissions_tenant_id_fkey")

    drop constraint(:form_submissions, "form_submissions_user_tenant_id_fkey")

    drop constraint(:form_submissions, "form_submissions_form_id_fkey")

    drop table(:form_submissions, prefix: prefix())
  end
end
