defmodule HousingApp.Repo.TenantMigrations.AddProductToRooms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms, prefix: prefix()) do
      add :product_id,
          references(:products,
            column: :id,
            name: "rooms_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:rooms, "rooms_product_id_fkey")

    alter table(:rooms, prefix: prefix()) do
      remove :product_id
    end
  end
end