defmodule HousingApp.Repo.TenantMigrations.AddRoommateAndCreatedByToBookings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bookings, prefix: prefix()) do
      add :roommate_group_id,
          references(:roommate_groups,
            column: :id,
            name: "bookings_roommate_group_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :created_by_id,
          references(:user_tenants,
            column: :id,
            name: "bookings_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bookings, "bookings_roommate_group_id_fkey")

    drop constraint(:bookings, "bookings_created_by_id_fkey")

    alter table(:bookings, prefix: prefix()) do
      remove :created_by_id
      remove :roommate_group_id
    end
  end
end