defmodule HousingApp.Repo.TenantMigrations.AddMissingUniqueChecks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:profiles, [:user_tenant_id],
             name: "profiles_unique_user_tenant_index"
           )
  end

  def down do
    drop_if_exists unique_index(:profiles, [:user_tenant_id],
                     name: "profiles_unique_user_tenant_index"
                   )
  end
end
