defmodule HousingApp.Repo.TenantMigrations.RemoveAshArchival do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:profiles, ["data"], name: "profiles_data_index")

    create index(:profiles, ["data"], using: "GIN")

    drop_if_exists unique_index(:profiles, [:user_tenant_id],
                     name: "profiles_unique_user_tenant_index"
                   )

    create unique_index(:profiles, [:user_tenant_id], name: "profiles_unique_user_tenant_index")
  end

  def down do
    drop_if_exists unique_index(:profiles, [:user_tenant_id],
                     name: "profiles_unique_user_tenant_index"
                   )

    create unique_index(:profiles, [:user_tenant_id],
             where: "archived_at IS NULL",
             name: "profiles_unique_user_tenant_index"
           )
  end
end
