defmodule HousingApp.Repo.TenantMigrations.AddStepsToApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applications, prefix: prefix()) do
      add :steps, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:applications, prefix: prefix()) do
      remove :steps
    end
  end
end