defmodule HousingApp.Repo.TenantMigrations.AddDataToProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:profiles, prefix: prefix()) do
      remove :roles
      add :data, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:profiles, prefix: prefix()) do
      remove :data
      add :roles, {:array, :text}, null: false, default: []
    end
  end
end
