defmodule HousingApp.Repo.TenantMigrations.AddManagementProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profiles, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :user_tenant_id,
          references(:user_tenants,
            column: :id,
            name: "profiles_user_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:profiles, "profiles_user_tenant_id_fkey")

    drop table(:profiles, prefix: prefix())
  end
end
