defmodule HousingApp.Repo.TenantMigrations.AddAccountingProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :description, :text, default: ""
      add :rate, :decimal, null: false, default: "0"
      add :data, :map, null: false, default: %{}
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :archived_at, :utc_datetime_usec

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "products_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:products, [:name], name: "products_unique_by_name_index")
  end

  def down do
    drop_if_exists unique_index(:products, [:name], name: "products_unique_by_name_index")

    drop constraint(:products, "products_tenant_id_fkey")

    drop table(:products, prefix: prefix())
  end
end