defmodule HousingApp.Repo.TenantMigrations.CreateRoleQueriesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:role_queries, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "role_queries_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_tenant_role_id,
          references(:user_tenant_roles,
            column: :id,
            name: "role_queries_user_tenant_role_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :common_query_id,
          references(:common_queries,
            column: :id,
            name: "role_queries_common_query_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :archived_at, :utc_datetime_usec
    end

    create index(:role_queries, ["user_tenant_role_id"])

    create unique_index(:role_queries, [:user_tenant_role_id, :common_query_id],
             name: "role_queries_unique_by_role_and_query_index"
           )
  end

  def down do
    drop_if_exists unique_index(:role_queries, [:user_tenant_role_id, :common_query_id],
                     name: "role_queries_unique_by_role_and_query_index"
                   )

    drop constraint(:role_queries, "role_queries_tenant_id_fkey")

    drop constraint(:role_queries, "role_queries_user_tenant_role_id_fkey")

    drop constraint(:role_queries, "role_queries_common_query_id_fkey")

    drop_if_exists index(:role_queries, ["user_tenant_role_id"],
                     name: "role_queries_user_tenant_role_id_index"
                   )

    drop table(:role_queries, prefix: prefix())
  end
end
