defmodule HousingApp.Repo.TenantMigrations.AddVariablesToForms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forms, prefix: prefix()) do
      add :variables, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:forms, prefix: prefix()) do
      remove :variables
    end
  end
end