defmodule HousingApp.Repo.TenantMigrations.CreateSelectionProcessTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:selection_processes, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "selection_processes_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
      add :name, :text, null: false
      add :description, :text, default: ""
      add :process, :text, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:selection_processes, "selection_processes_tenant_id_fkey")

    drop table(:selection_processes, prefix: prefix())
  end
end
