defmodule HousingApp.Repo.TenantMigrations.RenameInventoryCriteriaTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table("inventory_criteria", prefix: prefix()), to: table("selection_criteria", prefix: prefix())
  end

  def down do
    rename table("selection_criteria", prefix: prefix()), to: table("inventory_criteria", prefix: prefix())
  end
end
