defmodule HousingApp.Repo.TenantMigrations.ChangeCriterionField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:selection_processes, prefix: prefix()) do
      add :criterion, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:selection_processes, prefix: prefix()) do
      remove :criterion
    end
  end
end