defmodule HousingApp.Repo.Migrations.AddApiKeyToUserTenants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_tenants) do
      add :api_key, :text
    end

    create unique_index(:user_tenants, [:api_key],
             where: "api_key IS NOT NULL",
             name: "user_tenants_unique_api_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_tenants, [:api_key],
                     name: "user_tenants_unique_api_key_index"
                   )

    alter table(:user_tenants) do
      remove :api_key
    end
  end
end
