defmodule HousingApp.Repo.Migrations.RenameUserTenantRoleToType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:user_tenants), :role, to: :user_type
  end

  def down do
    rename table(:user_tenants), :user_type, to: :role
  end
end