defmodule HousingApp.Repo.Migrations.AddRolesToProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:user_tenants, ["tenant_id", "roles"],
                     name: "user_tenants_tenant_id_roles_index"
                   )

    alter table(:user_tenants) do
      remove :roles
    end
  end

  def down do
    alter table(:user_tenants) do
      add :roles, {:array, :text}, null: false, default: []
    end

    create index(:user_tenants, ["tenant_id", "roles"], using: "GIN")
  end
end
