defmodule HousingApp.Repo.Migrations.AddTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_tenants) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:tenants) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:tenants) do
      remove :updated_at
      remove :created_at
    end

    alter table(:user_tenants) do
      remove :updated_at
      remove :created_at
    end
  end
end