defmodule HousingApp.Repo.Migrations.AddRolesToUserTenants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_tenants) do
      add :roles, {:array, :text}, null: false, default: []
    end

    create index(:user_tenants, ["roles"], using: "GIN")
  end

  def down do
    drop_if_exists index(:user_tenants, ["roles"], name: "user_tenants_roles_index")

    alter table(:user_tenants) do
      remove :roles
    end
  end
end
